### ISSUE TITLE
The code file provided is incomplete

### ISSUE THREAD

**Issue by ccoverflow** [mayakapoor/flurry#1]
I can not find the webhost.py and networkhost.py in this project. But you mentioned both python flies in the README and in the video presentation of your paper.

**Comment by mayakapoor** [comment]
Hi! I have been working on updating the API since the referenced paper has been published. This commit and the attached documentation are from the version that I used for the paper. https://github.com/mayakapoor/flurry/commit/42a548d441447defd4b6b3ef8841f6c5c353ed42

I am still working on documentation and release notes for the new API, but experimentally the most recent commit to main has some example calls in main.py. I am re-organizing things in a way that I think will end up being more flexible which is why the files are changing around.
